### ISSUE TITLE
interp: unexpected array variable and subshell interaction

### ISSUE THREAD

**Issue by lboulard** [mvdan/sh#772]
Hi,

Running this sample on Windows 10 computer.

I reproduce unexpected behavior when using array and subshell.
I create a small example to reproduce behavior.

```sh
# gosh.test.sh
fn() {
  local p arg
  p="$1"
  shift
  for arg in "$@"; do echo "$p$arg"; done
}

VAR=(0 1 2 3)
fn a/ "${VAR[@]}"
var="$(fn b/ "${VAR[@]}")"
var1=($(fn c/ "${VAR[@]}"))
echo "-- ${#var}/${#var[@]} var=${var[@]}"
echo "-- ${#var1}/${#var1[@]} var1=${var1[@]}"
```

When running with `gosh`:

```
C:▶ gosh gosh.test.sh
a/0
a/1
a/2
a/3
-- 15/4 var=b/0
b/1
b/2
b/3 1 2 3
-- 5/7 var1=c/b/0 b/1 b/2 b/3 c/1 c/2 c/3
```

I expected this input like this one running with `bash` from MSYS2 installation.

```
C:▶ C:\msys64\usr\bin\bash gosh.test.sh
a/0
a/1
a/2
a/3
-- 15/1 var=b/0
b/1
b/2
b/3
-- 3/4 var1=c/0 c/1 c/2 c/3
```

There is a difficult interaction between case insensitivity of receiving variable, assignment to array typed variable and word splitting an spaces.

I was not able to separate bugs interaction more to have a better issue reporting.
Sorry.

**Comment by mvdan** [comment]
Thanks for filing a bug :)

Perhaps interesting to @riacataquian since she fixed an array bug recently.

**Comment by mvdan** [comment]
I believe this has been fixed at some point since you filed the bug:

```
$ gosh f.bash; echo ==; bash f.bash
a/0
a/1
a/2
a/3
-- 15/1 var=b/0
b/1
b/2
b/3
-- 3/4 var1=c/0 c/1 c/2 c/3
==
a/0
a/1
a/2
a/3
-- 15/1 var=b/0
b/1
b/2
b/3
-- 3/4 var1=c/0 c/1 c/2 c/3
```

**Comment by lboulard** [comment]
Thanks for going back in time to review this bug. Bisecting lead to this commit as fix: https://github.com/mvdan/sh/commit/3d8d47845eeb99f4d8c9dca764ced953c7445f15

Please, notes that original test still buggy. Variables seems to be case insensitive for `gosh`.
May be this is expected.

```bash
# gosh.test.sh
fn() {
  local p arg
  p="$1"
  shift
  for arg in "$@"; do echo "$p$arg"; done
}

VAR=(0 1 2 3)
fn a/ "${VAR[@]}"
var="$(fn b/ "${VAR[@]}")"
var1=($(fn c/ "${VAR[@]}"))
echo "-- ${#var}/${#var[@]} var=${var[@]}"
echo "-- ${#var1}/${#var1[@]} var1=${var1[@]}"
```

```text
$ ./gosh gosh.test.sh; echo ==; bash gosh.test.sh
a/0
a/1
a/2
a/3
-- 15/4 var=b/0
b/1
b/2
b/3 1 2 3
-- 5/7 var1=c/b/0 b/1 b/2 b/3 c/1 c/2 c/3
==
a/0
a/1
a/2
a/3
-- 15/1 var=b/0
b/1
b/2
b/3
-- 3/4 var1=c/0 c/1 c/2 c/3
```

If I avoid names collision, this works.

```bash
# gosh2.test.sh
fn() {
  local p arg
  p="$1"
  shift
  for arg in "$@"; do echo "$p$arg"; done
}

VAR2=(0 1 2 3)
fn a/ "${VAR2[@]}"
var="$(fn b/ "${VAR2[@]}")"
var1=($(fn c/ "${VAR2[@]}"))
echo "-- ${#var}/${#var[@]} var=${var[@]}"
echo "-- ${#var1}/${#var1[@]} var1=${var1[@]}"
```

```test
$ ./gosh gosh.test2.sh; echo ==; bash gosh.test2.sh
a/0
a/1
a/2
a/3
-- 15/1 var=b/0
b/1
b/2
b/3
-- 3/4 var1=c/0 c/1 c/2 c/3
==
a/0
a/1
a/2
a/3
-- 15/1 var=b/0
b/1
b/2
b/3
-- 3/4 var1=c/0 c/1 c/2 c/3
```

Thanks for your time.

**Comment by mvdan** [comment]
What version of gosh are you with? With master (ca2088cedd4f6bf1c771c193dd017fc4636685a0) built with Go 1.20.3 I still get the same as bash:

```
$ gosh f.bash
a/0
a/1
a/2
a/3
-- 15/1 var=b/0
b/1
b/2
b/3
-- 3/4 var1=c/0 c/1 c/2 c/3
```

**Comment by lboulard** [comment]
Tests were on Windows. On [master](https://github.com/mvdan/sh/commit/ca2088cedd4f6bf1c771c193dd017fc4636685a0) branch of this morning.

Oh ! Tested on Linux. And issue does not happen on this platform! Really weird.

**Comment by mvdan** [comment]
Hm, it's possible that this is a bug that only happens on Windows.

**Comment by lboulard** [comment]
Forgot to mention using Go1.20.3 on both platforms.

Certainly. Environment variables are case insensitive on native Windows platform.
Bash when run in MSYS2/CYGWIN emulation use alternate way of sharing environment to have case sensitive variables.

I think you can set this case as solved.
Issue was propagation of variables content in sub shell. not case sensitivity.

**Comment by mvdan** [comment]
Ah I see, that makes sense.

**Comment by mvdan** [comment]
Also note that we do have a bit of special behavior for Windows when looking up variables in the interpreter: https://github.com/mvdan/sh/blob/45feae90b7877d090a0f93a51835579043d3d5a1/interp/vars.go#L166

**Comment by lboulard** [comment]
OK. That explain behavior. Thanks for hint.

In POSIX shell, environment variables are case sensitive.
But running gosh in windows, you have to choose how to export variables to created native processes.

Best answer for portability would be having case sensitive variables "internally" when interpreting shell (and subshell?). Then only "uppercase" variables declared as exported for native processes.
Need to coerce internals and exported environment variables at process creation.

**Comment by mvdan** [comment]
Yeah, that sounds right. I'll reopen once again.
